# Generated by Django 2.2.10 on 2021-04-19 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=200)),
                ('sendFrom', models.CharField(max_length=200)),
                ('stationName', models.CharField(max_length=200)),
                ('senderName', models.CharField(max_length=200)),
                ('senderPhone', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('destinationStaff', models.CharField(max_length=200)),
                ('destinationStaffPhone', models.CharField(max_length=200)),
                ('receiverName', models.CharField(max_length=200)),
                ('receiverPhone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='stationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationName', models.CharField(max_length=200)),
                ('stationLocation', models.CharField(max_length=200)),
                ('stationStaff', models.CharField(max_length=200)),
                ('stationPhone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='smsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=200)),
                ('receiverPhone', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('code', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('destinationKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stationModel')),
            ],
        ),
        migrations.CreateModel(
            name='paymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('paid', models.CharField(max_length=200)),
                ('balance', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('paymentMeans', models.CharField(max_length=200)),
                ('itemKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.itemModel')),
            ],
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='destinationKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stationModel'),
        ),
    ]
