# Generated by Django 2.2.10 on 2021-04-19 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pricingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromStation', models.CharField(max_length=200)),
                ('fromLocation', models.CharField(max_length=200)),
                ('toStatation', models.CharField(max_length=200)),
                ('toLocation', models.CharField(max_length=200)),
                ('pricing', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemmodel',
            name='destinationKey',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='itemKey',
        ),
        migrations.RemoveField(
            model_name='smsmodel',
            name='destinationKey',
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='destinantionStationKey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.stationModel'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='smsmodel',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stationmodel',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='smsmodel',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
