# Generated by Django 2.2.10 on 2021-04-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210419_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmodel',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='smsmodel',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
