# Generated by Django 2.2.10 on 2021-04-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210423_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='status',
            field=models.CharField(default='On Fleet', max_length=200),
        ),
    ]
