# Generated by Django 2.2.10 on 2021-04-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210424_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='itemType',
            field=models.CharField(choices=[('Parcel', 'Parcel'), ('Courier', 'Courier')], default='Parcel', max_length=200),
        ),
    ]
